In [1]:
%run -i 'src/SPV.py'

In [3]:
df = pd.read_csv('data/clean_2017_hourly.csv')
#df = df.drop(columns=['grid'])

In [4]:
df.head()

   dataid            localhour  gen       use
0      26  2017-01-01 00:00:00  0.0  1.788817
1      26  2017-01-01 01:00:00  0.0  1.223917
2      26  2017-01-01 02:00:00  0.0  0.668367
3      26  2017-01-01 03:00:00  0.0  0.478667
4      26  2017-01-01 04:00:00  0.0  0.416283

In [5]:
df_systemsize = pd.read_csv('data/pv_system_size.csv')

In [8]:
df.shape

(1698276, 4)

In [9]:
df_systemsize.shape

(194, 2)

In [10]:
df_merge = pd.merge(df, df_systemsize, on='dataid', how='left')

In [13]:
df_merge.head()

   dataid            localhour  gen       use  pv_system_size
0      26  2017-01-01 00:00:00  0.0  1.788817             6.0
1      26  2017-01-01 01:00:00  0.0  1.223917             6.0
2      26  2017-01-01 02:00:00  0.0  0.668367             6.0
3      26  2017-01-01 03:00:00  0.0  0.478667             6.0
4      26  2017-01-01 04:00:00  0.0  0.416283             6.0

In [15]:
df_merge['gen_per_kW'] = (df_merge.gen/df_merge.pv_system_size)
df_merge.head()

   dataid            localhour  gen       use  pv_system_size  gen_per_kW
0      26  2017-01-01 00:00:00  0.0  1.788817             6.0         0.0
1      26  2017-01-01 01:00:00  0.0  1.223917             6.0         0.0
2      26  2017-01-01 02:00:00  0.0  0.668367             6.0         0.0
3      26  2017-01-01 03:00:00  0.0  0.478667             6.0         0.0
4      26  2017-01-01 04:00:00  0.0  0.416283             6.0         0.0

In [19]:
df_merge.to_csv('clean_2017_hourly_normalized.csv', sep=',', index=False)

In [16]:
df_summary = df_merge.groupby(['dataid']).mean()

In [17]:
df_summary

             gen       use  pv_system_size  gen_per_kW
dataid
26      0.847714  1.288759           6.000    0.141286
77      0.465683  1.537219           4.000    0.116421
93      0.779276  1.043385           5.800    0.134358
114     0.541586  1.222701           5.200    0.104151
171     0.854426  0.888597           6.800    0.125651
252     0.758118  2.988667           5.200    0.145792
330     1.976162  2.199641          12.000    0.164680
370     0.713500  1.460676           6.000    0.118917
379     0.946026  1.789720           8.500    0.111297
499     0.569686  1.336673           6.200    0.091885
545     0.509184  1.506231           5.000    0.101837
547     0.328147  1.736274           2.300    0.142673
585     0.704969  1.107622           6.200    0.113705
668     0.955905  1.323639           8.000    0.119488
744     0.654527  1.073794           5.900    0.110937
781     0.907300  1.263709           5.600    0.162018
890     0.634448  1.185975           5.300    0.119707
974     1.051438  1.862407           6.200    0.169587
1103    0.590484  0.597760           4.800    0.123017
1169    0.571091  0.875921           3.885    0.146999
1192    0.906783  0.959083           7.200    0.125942
1354    0.854181  1.059756           6.000    0.142363
1415    0.507432  0.889790           3.500    0.144981
1714    0.757034  1.715570           6.000    0.126172
1718    0.882443  2.004264           7.200    0.122562
1792    0.940559  0.720071           6.200    0.151703
1800    1.283074  1.517833           7.600    0.168826
1801    1.411115  1.726700           9.000    0.156791
1879    0.547557  1.292279           4.000    0.136889
2018    1.153903  2.490242           7.900    0.146064
...          ...       ...             ...         ...
100102  0.923034  2.187265           7.500    0.123071
100108  1.447794  1.971539          11.000    0.131618
100109  0.971122  0.910042           8.600    0.112921
100111  1.358530  1.961215           8.650    0.157055
100121  0.685366  0.436797           5.400    0.126920
100135  0.682415  0.659674           5.600    0.121860
100153  1.634912  1.788484          12.400    0.131848
100175  0.484827  0.429376           5.000    0.096965
100177  0.850366  1.951523           6.200    0.137156
100178  1.322287  3.086472          11.000    0.120208
100179  0.797019  0.880402           6.000    0.132836
100183  0.321379  1.051008           4.000    0.080345
100189  0.540535  0.885740           4.600    0.117508
100207  1.238543  1.499245           8.000    0.154818
100212  0.741026  2.029612           5.600    0.132326
100213  1.705872  1.690367          12.000    0.142156
100214  1.047437  2.462190           8.800    0.119027
100220  0.397696  0.984038           4.000    0.099424
100221  1.243910  3.192554           8.250    0.150777
100224  1.017206  1.249508           8.000    0.127151
100225  0.416996  0.761197           4.200    0.099285
100226  1.375112  2.494540          11.200    0.122778
100238  1.669643  4.255082          12.000    0.139137
100241  2.180964  3.567238          16.200    0.134627
100244  1.243749  1.392622           8.800    0.141335
100251  0.333459  0.666427           3.600    0.092628
100252  1.136986  1.649263           7.800    0.145767
100253  0.566920  1.093539           4.400    0.128846
100256  0.820028  0.891464           6.000    0.136671
100267  0.887205  1.001962           6.600    0.134425

[194 rows x 4 columns]

In [42]:
df4 = pd.read_csv('data/clean_2017_hourly_with_capacity.csv')

In [43]:
df4.head()

   dataid          local_1hour  gen       use  pv_system_size  gen_per_kw
0      26  2017-01-01 00:00:00  0.0  1.788817             6.0         0.0
1      26  2017-01-01 01:00:00  0.0  1.223917             6.0         0.0
2      26  2017-01-01 02:00:00  0.0  0.668367             6.0         0.0
3      26  2017-01-01 03:00:00  0.0  0.478667             6.0         0.0
4      26  2017-01-01 04:00:00  0.0  0.416283             6.0         0.0

In [44]:
df5 = df4.groupby(['dataid']).mean()

In [45]:
df5.head()

             gen       use  pv_system_size  gen_per_kw
dataid
26      0.847714  1.288759           6.000    0.141286
744     0.654527  1.073794           5.900    0.110937
781     0.907300  1.263709           5.600    0.162018
1103    0.590484  0.597760           4.800    0.123017
1169    0.571091  0.875921           3.885    0.146999

In [46]:
df5.shape

(56, 4)

In [47]:
df5

             gen       use  pv_system_size  gen_per_kw
dataid
26      0.847714  1.288759           6.000    0.141286
744     0.654527  1.073794           5.900    0.110937
781     0.907300  1.263709           5.600    0.162018
1103    0.590484  0.597760           4.800    0.123017
1169    0.571091  0.875921           3.885    0.146999
1714    0.757034  1.715570           6.000    0.126172
2129    0.842347  1.818704           6.200    0.135862
2470    0.494685  0.755511           3.500    0.141339
2557    0.775453  1.260642           5.170    0.149991
2638    0.748009  1.146444           4.600    0.162611
2814    0.861604  1.244612           6.200    0.138968
3009    0.945267  1.183935           6.100    0.154962
3036    0.611389  1.274800           4.500    0.135864
3134    0.841796  0.867909           5.750    0.146399
3310    0.844372  1.075570           6.200    0.136189
3368    0.724933  0.709184           5.000    0.144987
3482    0.720957  0.794984           5.130    0.140537
3506    0.947115  1.193708           6.200    0.152761
3649    1.106549  1.723215           7.500    0.147540
3719    0.942575  1.681049           6.500    0.145012
3736    0.803876  1.349652           5.900    0.136250
3967    0.872506  1.424198           6.200    0.140727
4336    0.448132  1.469227           3.150    0.142588
4830    0.691722  1.140757           4.000    0.172930
5218    0.850878  0.762551           5.500    0.154705
5246    0.837402  1.890762           6.200    0.135065
5448    0.740608  1.494248           5.160    0.143529
5615    0.577931  1.480511           6.250    0.092469
5738    0.822888  1.279893           6.000    0.137148
5749    0.398825  1.766992           3.200    0.124633
5784    1.504679  2.474599          11.000    0.136789
6248    1.214658  1.777932           6.800    0.178626
6348    0.522000  1.610926           7.290    0.071605
6691    0.783098  2.367094           5.000    0.156620
7429    1.023063  1.176081           7.200    0.142092
7541    0.782571  1.598086           6.250    0.125211
7731    0.855859  0.912120           6.800    0.125862
7741    0.907464  0.566475           6.000    0.151244
7875    0.276464  1.191537           5.000    0.055293
7989    0.863670  1.268204           6.240    0.138409
8046    1.327615  1.186454          14.400    0.092196
8084    1.416899  1.285684           8.800    0.161011
8243    0.939070  0.862755           6.100    0.153946
8626    1.006875  1.243159           6.400    0.157324
8829    0.989852  1.119846           6.200    0.159654
8857    1.308493  1.370732          11.100    0.117882
9019    0.274025  1.001345           2.300    0.119141
9052    0.896155  1.094138           6.000    0.149359
9134    0.766743  1.418493           5.000    0.153349
9647    1.049605  3.010063           6.300    0.166604
9737    1.521863  2.784585          10.000    0.152186
9776    0.968758  3.342584           6.000    0.161460
9932    0.667614  0.676282           5.200    0.128387
9937    0.906388  0.922012           8.625    0.105089
9939    0.639571  1.380727           6.000    0.106595
9942    0.062927  1.096937           0.500    0.125854

In [34]:
df6 = df3.groupby(['dataid']).mean()

In [35]:
df6.shape

(194, 2)

In [36]:
df6.head()

             gen       use
dataid
26      0.847714  1.288759
77      0.465683  1.537219
93      0.779276  1.043385
114     0.541586  1.222701
171     0.854426  0.888597

In [38]:
df5.to_csv('summary_2017_mean_with_capacity.csv', sep=',')

In [39]:
df6.to_csv('summary_2017_mean.csv', sep=',')

In [40]:
df5

             gen       use  pv_system_size  gen_per_kw
dataid
26      0.847714  1.288759           6.000    0.141286
744     0.654527  1.073794           5.900    0.110937
781     0.907300  1.263709           5.600    0.162018
1103    0.590484  0.597760           4.800    0.123017
1169    0.571091  0.875921           3.885    0.146999
1714    0.757034  1.715570           6.000    0.126172
2129    0.842347  1.818704           6.200    0.135862
2470    0.494685  0.755511           3.500    0.141339
2557    0.775453  1.260642           5.170    0.149991
2638    0.748009  1.146444           4.600    0.162611
2814    0.861604  1.244612           6.200    0.138968
3009    0.945267  1.183935           6.100    0.154962
3036    0.611389  1.274800           4.500    0.135864
3134    0.841796  0.867909           5.750    0.146399
3310    0.844372  1.075570           6.200    0.136189
3368    0.724933  0.709184           5.000    0.144987
3482    0.720957  0.794984           5.130    0.140537
3506    0.947115  1.193708           6.200    0.152761
3649    1.106549  1.723215           7.500    0.147540
3719    0.942575  1.681049           6.500    0.145012
3736    0.803876  1.349652           5.900    0.136250
3967    0.872506  1.424198           6.200    0.140727
4336    0.448132  1.469227           3.150    0.142588
4830    0.691722  1.140757           4.000    0.172930
5218    0.850878  0.762551           5.500    0.154705
5246    0.837402  1.890762           6.200    0.135065
5448    0.740608  1.494248           5.160    0.143529
5615    0.577931  1.480511           6.250    0.092469
5738    0.822888  1.279893           6.000    0.137148
5749    0.398825  1.766992           3.200    0.124633
5784    1.504679  2.474599          11.000    0.136789
6248    1.214658  1.777932           6.800    0.178626
6348    0.522000  1.610926           7.290    0.071605
6691    0.783098  2.367094           5.000    0.156620
7429    1.023063  1.176081           7.200    0.142092
7541    0.782571  1.598086           0.625    1.252114
7731    0.855859  0.912120           6.800    0.125862
7741    0.907464  0.566475           6.000    0.151244
7875    0.276464  1.191537           5.000    0.055293
7989    0.863670  1.268204           6.240    0.138409
8046    1.327615  1.186454          14.400    0.092196
8084    1.416899  1.285684           8.800    0.161011
8243    0.939070  0.862755           6.100    0.153946
8626    1.006875  1.243159           6.400    0.157324
8829    0.989852  1.119846           6.200    0.159654
8857    1.308493  1.370732          11.100    0.117882
9019    0.274025  1.001345           2.300    0.119141
9052    0.896155  1.094138           6.000    0.149359
9134    0.766743  1.418493           5.000    0.153349
9647    1.049605  3.010063           6.300    0.166604
9737    1.521863  2.784585          10.000    0.152186
9776    0.968758  3.342584           6.000    0.161460
9932    0.667614  0.676282           5.200    0.128387
9937    0.906388  0.922012           8.625    0.105089
9939    0.639571  1.380727           6.000    0.106595
9942    0.062927  1.096937           7.000    0.008990

             gen       use
dataid
26      0.847714  1.288759
77      0.465683  1.537219
93      0.779276  1.043385
114     0.541586  1.222701
171     0.854426  0.888597
252     0.758118  2.988667
330     1.976162  2.199641
370     0.713500  1.460676
379     0.946026  1.789720
499     0.569686  1.336673
545     0.509184  1.506231
547     0.328147  1.736274
585     0.704969  1.107622
668     0.955905  1.323639
744     0.654527  1.073794
781     0.907300  1.263709
890     0.634448  1.185975
974     1.051438  1.862407
1103    0.590484  0.597760
1169    0.571091  0.875921
1192    0.906783  0.959083
1354    0.854181  1.059756
1415    0.507432  0.889790
1714    0.757034  1.715570
1718    0.882443  2.004264
1792    0.940559  0.720071
1800    1.283074  1.517833
1801    1.411115  1.726700
1879    0.547557  1.292279
2018    1.153903  2.490242
...          ...       ...
100102  0.923034  2.187265
100108  1.447794  1.971539
100109  0.971122  0.910042
100111  1.358530  1.961215
100121  0.685366  0.436797
100135  0.682415  0.659674
100153  1.634912  1.788484
100175  0.484827  0.429376
100177  0.850366  1.951523
100178  1.322287  3.086472
100179  0.797019  0.880402
100183  0.321379  1.051008
100189  0.540535  0.885740
100207  1.238543  1.499245
100212  0.741026  2.029612
100213  1.705872  1.690367
100214  1.047437  2.462190
100220  0.397696  0.984038
100221  1.243910  3.192554
100224  1.017206  1.249508
100225  0.416996  0.761197
100226  1.375112  2.494540
100238  1.669643  4.255082
100241  2.180964  3.567238
100244  1.243749  1.392622
100251  0.333459  0.666427
100252  1.136986  1.649263
100253  0.566920  1.093539
100256  0.820028  0.891464
100267  0.887205  1.001962

[194 rows x 2 columns]

In [50]:
df7 = pd.merge(df6, df5, on='dataid', how='left')

In [52]:
df8 = df7.drop(columns=['gen_y','use_y'])

In [53]:
df8

           gen_x     use_x  pv_system_size  gen_per_kw
dataid
26      0.847714  1.288759           6.000    0.141286
77      0.465683  1.537219             NaN         NaN
93      0.779276  1.043385             NaN         NaN
114     0.541586  1.222701             NaN         NaN
171     0.854426  0.888597             NaN         NaN
252     0.758118  2.988667             NaN         NaN
330     1.976162  2.199641             NaN         NaN
370     0.713500  1.460676             NaN         NaN
379     0.946026  1.789720             NaN         NaN
499     0.569686  1.336673             NaN         NaN
545     0.509184  1.506231             NaN         NaN
547     0.328147  1.736274             NaN         NaN
585     0.704969  1.107622             NaN         NaN
668     0.955905  1.323639             NaN         NaN
744     0.654527  1.073794           5.900    0.110937
781     0.907300  1.263709           5.600    0.162018
890     0.634448  1.185975             NaN         NaN
974     1.051438  1.862407             NaN         NaN
1103    0.590484  0.597760           4.800    0.123017
1169    0.571091  0.875921           3.885    0.146999
1192    0.906783  0.959083             NaN         NaN
1354    0.854181  1.059756             NaN         NaN
1415    0.507432  0.889790             NaN         NaN
1714    0.757034  1.715570           6.000    0.126172
1718    0.882443  2.004264             NaN         NaN
1792    0.940559  0.720071             NaN         NaN
1800    1.283074  1.517833             NaN         NaN
1801    1.411115  1.726700             NaN         NaN
1879    0.547557  1.292279             NaN         NaN
2018    1.153903  2.490242             NaN         NaN
...          ...       ...             ...         ...
100102  0.923034  2.187265             NaN         NaN
100108  1.447794  1.971539             NaN         NaN
100109  0.971122  0.910042             NaN         NaN
100111  1.358530  1.961215             NaN         NaN
100121  0.685366  0.436797             NaN         NaN
100135  0.682415  0.659674             NaN         NaN
100153  1.634912  1.788484             NaN         NaN
100175  0.484827  0.429376             NaN         NaN
100177  0.850366  1.951523             NaN         NaN
100178  1.322287  3.086472             NaN         NaN
100179  0.797019  0.880402             NaN         NaN
100183  0.321379  1.051008             NaN         NaN
100189  0.540535  0.885740             NaN         NaN
100207  1.238543  1.499245             NaN         NaN
100212  0.741026  2.029612             NaN         NaN
100213  1.705872  1.690367             NaN         NaN
100214  1.047437  2.462190             NaN         NaN
100220  0.397696  0.984038             NaN         NaN
100221  1.243910  3.192554             NaN         NaN
100224  1.017206  1.249508             NaN         NaN
100225  0.416996  0.761197             NaN         NaN
100226  1.375112  2.494540             NaN         NaN
100238  1.669643  4.255082             NaN         NaN
100241  2.180964  3.567238             NaN         NaN
100244  1.243749  1.392622             NaN         NaN
100251  0.333459  0.666427             NaN         NaN
100252  1.136986  1.649263             NaN         NaN
100253  0.566920  1.093539             NaN         NaN
100256  0.820028  0.891464             NaN         NaN
100267  0.887205  1.001962             NaN         NaN

[194 rows x 4 columns]

In [55]:
df8.to_csv('temporal.csv', sep=',')